apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-userservice:5432/innowise_user_service"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgresql"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  AUTH_SERVICE_VALIDATE_URL: "http://auth-service:8080/api/v1/auth/validate"
  SERVER_PORT: "8081"
  DB_HOST: "postgres-userservice"
  DB_PORT: "5432"
  DB_NAME: "innowise_user_service"