apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orderservice
  template:
    metadata:
      labels:
        app: postgres-orderservice
    spec:
      priorityClassName: high-priority
      containers:
        - name: postgres
          image: 'postgres:15'
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: order-service-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-service-secret
                  key: DB_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-order-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-orderservice
spec:
  ports:
    - port: 5435
      targetPort: 5432
  selector:
    app: postgres-orderservice
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-order-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi